# Generated by Django 3.1.2 on 2021-02-13 05:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newKey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='keys',
            name='life',
            field=models.DurationField(default=datetime.timedelta(0, 3600)),
        ),
    ]
