# Generated by Django 3.1.2 on 2021-02-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newKey', '0002_keys_life'),
    ]

    operations = [
        migrations.AddField(
            model_name='keys',
            name='maxScanned',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='keys',
            name='scanned',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='keys',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='keys',
            name='key',
            field=models.CharField(default='a5zMqTgLMPIGPyBUkzoc11u5C1_vei895WXIsOeyCqQ', max_length=44),
        ),
    ]
