# Generated by Django 3.1.2 on 2021-02-14 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newKey', '0003_auto_20210214_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keys',
            name='key',
            field=models.CharField(default='40DaHfg3t7B5a6QiYZmyBhs4RfFoUtLZY_QWrX5Mbgo', max_length=44),
        ),
    ]
