# Generated by Django 3.1.2 on 2021-02-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newKey', '0005_auto_20210214_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keys',
            name='key',
            field=models.CharField(default='TzquEsL5ulMEoRiCYCvq_4-JTBAEA-gx0wSY3z9eDcQ', max_length=44),
        ),
    ]
