# Generated by Django 3.1.2 on 2021-02-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newKey', '0007_auto_20210214_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='keys',
            name='createdBy',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='keys',
            name='token',
            field=models.CharField(max_length=44),
        ),
    ]
