# Generated by Django 3.1.1 on 2020-09-27 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='Пароль',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
