# Generated by Django 3.1.2 on 2020-11-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lists',
            name='owner',
            field=models.ManyToManyField(null=True, to='profiles.Profile'),
        ),
    ]
